### ISSUE TITLE
Can't close a ticket

### ISSUE THREAD

**Issue by SmallSansSerif** [Sabbertran/gReqBukkit#4]
I get an error when closing a ticket

[10:02:18] [Server thread/INFO]: SmallSansSerif issued server command: /tickets close 4 this is it
[10:02:18] [Server thread/ERROR]: null
java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3709) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3693) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4544) ~[spigot.jar:git-Spigot-44c59bf-1880a9c]
    at me.sabbertran.greqbukkit.GReqBukkit.closeTicket(GReqBukkit.java:426) [gReqBukkit.jar:?]
    at me.sabbertran.greqbukkit.commands.TicketsCommand.onCommand(TicketsCommand.java:152) [gReqBukkit.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-44c59bf-1880a9c]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by SmallSansSerif** [comment]
I see you are on v1.3.4 now.. so maybe you already got this fixed.
